public class sum_numbers {
    
    public static void add(Integer r,Integer y){                   //addition of two numbers
        Integer a1 = r, b2 = y;
        Integer c = a1 + b2;
        system.debug('sum of two numbers = ' + c);
    }
    
    public static void sub(Decimal n1,Decimal n2){                 //subraction of two numbers
        Decimal s1 = n1, s2 = n2;
        Decimal d = s1 - s2;
        system.debug('suburaction of two values = '+ d);
    }
    
    public static void multiply(Integer w1,Integer y1){               //Multiplly two numbers 
        Integer t1= 322;
        Integer t2 = 232;
        Integer c = t1 * t2;
        system.debug('mulitply of two numbers = ' + c);
    }
    public static void divide(){
        Decimal d1= 23, d2 = 232;
        Decimal f= d1 / d2;
        system.debug('division of two numbers are ' +f);
    }
    
}